# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Feed

import flatbuffers

# /// Motion state of Objects
class Motion(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMotion(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Motion()
        x.Init(buf, n + offset)
        return x

    # Motion
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Position
    # Motion
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .Position import Position
            obj = Position()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Speed [m/s]
    # Motion
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

# /// Longitudinal acceleration [m/s^2]
    # Motion
    def Acceleration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

# /// Heading [deg]
    # Motion
    def Heading(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

# /// Yaw rate [deg/s]
    # Motion
    def YawRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def MotionStart(builder): builder.StartObject(5)
def MotionAddPosition(builder, position): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)
def MotionAddSpeed(builder, speed): builder.PrependFloat64Slot(1, speed, 0.0)
def MotionAddAcceleration(builder, acceleration): builder.PrependFloat64Slot(2, acceleration, 0.0)
def MotionAddHeading(builder, heading): builder.PrependFloat64Slot(3, heading, 0.0)
def MotionAddYawRate(builder, yawRate): builder.PrependFloat64Slot(4, yawRate, 0.0)
def MotionEnd(builder): return builder.EndObject()
