# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Feed

# /// Object types
class ObjectType(object):
    Unknown = 0
    Vehicle = 1
    Pedestrian = 2
    Cyclist = 3
    Animal = 4
    Other = 5

