# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Feed

import flatbuffers

# /// Geospherical position
class Position(object):
    __slots__ = ['_tab']

    # Position
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Latitude [deg]
    # Position
    def Latitude(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
# /// Longitude [deg]
    # Position
    def Longitude(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreatePosition(builder, latitude, longitude):
    builder.Prep(8, 16)
    builder.PrependFloat64(longitude)
    builder.PrependFloat64(latitude)
    return builder.Offset()
