# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Feed

# /// Vehicle types
class VehicleType(object):
    Unknown = 0
    PassengerCar = 1
    Special = 2
    LightTruck = 3
    Truck = 4
    Motorcycle = 5
    Transit = 6
    FixedGuideway = 7
    Emergency = 8
    Infrastructure = 9
    Other = 10

